{{- if gt (int .Values.replicas) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "karpenter-ovhcloud.fullname" . }}
  labels:
    {{- include "karpenter-ovhcloud.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "karpenter-ovhcloud.selectorLabels" . | nindent 6 }}
{{- end }}
