apiVersion: v1
kind: Service
metadata:
  name: {{ include "karpenter-ovhcloud.fullname" . }}
  labels:
    {{- include "karpenter-ovhcloud.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
      protocol: TCP
    - name: http-health
      port: 8081
      targetPort: http-health
      protocol: TCP
  selector:
    {{- include "karpenter-ovhcloud.selectorLabels" . | nindent 4 }}
